version: "3.9"

services:
  backend:
    build:
      context: ../backend
    container_name: fintrack-backend
    ports:
      - "5000:5000"
    volumes:
      - ../backend:/app
      - ./output:/app/output
    environment:
      - FLASK_ENV=development

  redis:
    image: redis:7.2
    container_name: fintrack-redis
    ports:
      - "6379:6379"
  prometheus:
    image: prom/prometheus:latest
    container_name: fintrack-prometheus
    volumes:
      - ../monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: fintrack-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage: